# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.api.server_api import ServerApi


class TestServerApi(unittest.TestCase):
    """ServerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServerApi()

    def tearDown(self) -> None:
        pass

    def test_delete_server_monitorings(self) -> None:
        """Test case for delete_server_monitorings

        サーバーのサーバー監視情報を削除する
        """
        pass

    def test_get_server(self) -> None:
        """Test case for get_server

        サーバー情報を取得する
        """
        pass

    def test_get_server_interface(self) -> None:
        """Test case for get_server_interface

        サーバーのインターフェース情報を取得する
        """
        pass

    def test_get_server_interface_list(self) -> None:
        """Test case for get_server_interface_list

        サーバーのインターフェース情報一覧を取得する
        """
        pass

    def test_get_server_limitation(self) -> None:
        """Test case for get_server_limitation

        サーバーの制限情報を取得する
        """
        pass

    def test_get_server_list(self) -> None:
        """Test case for get_server_list

        サーバー情報一覧を取得する
        """
        pass

    def test_get_server_monitoring(self) -> None:
        """Test case for get_server_monitoring

        サーバーのサーバー監視情報を取得する
        """
        pass

    def test_get_server_monitoring_health(self) -> None:
        """Test case for get_server_monitoring_health

        サーバー監視の監視状態を取得する
        """
        pass

    def test_get_server_monitoring_list(self) -> None:
        """Test case for get_server_monitoring_list

        サーバーのサーバー監視情報一覧を取得する
        """
        pass

    def test_get_server_power_status(self) -> None:
        """Test case for get_server_power_status

        サーバーの電源状態を取得する
        """
        pass

    def test_get_server_video_device(self) -> None:
        """Test case for get_server_video_device

        サーバーのビデオデバイスの設定を取得する
        """
        pass

    def test_get_server_vnc_console_keymap(self) -> None:
        """Test case for get_server_vnc_console_keymap

        コンパネのVNCコンソールのキーマップ情報を取得する
        """
        pass

    def test_post_server_force_reboot(self) -> None:
        """Test case for post_server_force_reboot

        サーバーを強制再起動する
        """
        pass

    def test_post_server_monitoring(self) -> None:
        """Test case for post_server_monitoring

        サーバーのサーバー監視を作成する
        """
        pass

    def test_post_server_mount_disc(self) -> None:
        """Test case for post_server_mount_disc

        サーバーにディスクをマウントする
        """
        pass

    def test_post_server_power_on(self) -> None:
        """Test case for post_server_power_on

        サーバーを起動する
        """
        pass

    def test_post_server_shutdown(self) -> None:
        """Test case for post_server_shutdown

        サーバーをシャットダウンする
        """
        pass

    def test_put_server(self) -> None:
        """Test case for put_server

        サーバー情報を更新する
        """
        pass

    def test_put_server_interface(self) -> None:
        """Test case for put_server_interface

        サーバーのインターフェース情報を更新する
        """
        pass

    def test_put_server_ipv4_ptr(self) -> None:
        """Test case for put_server_ipv4_ptr

        サーバーのipv4の逆引きホスト名を更新する
        """
        pass

    def test_put_server_ipv6_ptr(self) -> None:
        """Test case for put_server_ipv6_ptr

        サーバーのipv6の逆引きホスト名を更新する
        """
        pass

    def test_put_server_monitoring(self) -> None:
        """Test case for put_server_monitoring

        サーバーのサーバー監視情報を更新する
        """
        pass

    def test_put_server_video_device(self) -> None:
        """Test case for put_server_video_device

        サーバーのビデオデバイスの設定を更新する
        """
        pass

    def test_put_server_vnc_console_keymap(self) -> None:
        """Test case for put_server_vnc_console_keymap

        コンパネのVNCコンソールのキーマップ情報を変更する
        """
        pass


if __name__ == '__main__':
    unittest.main()
