# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.role import Role

class TestRole(unittest.TestCase):
    """Role unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Role:
        """Test Role
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Role`
        """
        model = Role()
        if include_optional:
            return Role(
                id = 56,
                name = '',
                description = '',
                permission_filtering = 'enabled',
                allowed_permissions = ["get-server-list","get-server","put-server"],
                resource_filtering = 'enabled',
                allowed_resources = sakura_vps_client_py.models.role_allowed_resources.Role_allowed_resources(
                    servers = [1,2,3], 
                    switches = [1,2,3], 
                    nfs_servers = [1,2,3], )
            )
        else:
            return Role(
                id = 56,
                name = '',
                description = '',
                permission_filtering = 'enabled',
                allowed_permissions = ["get-server-list","get-server","put-server"],
                resource_filtering = 'enabled',
                allowed_resources = sakura_vps_client_py.models.role_allowed_resources.Role_allowed_resources(
                    servers = [1,2,3], 
                    switches = [1,2,3], 
                    nfs_servers = [1,2,3], ),
        )
        """

    def testRole(self):
        """Test Role"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
