# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.post_switch201_response import PostSwitch201Response

class TestPostSwitch201Response(unittest.TestCase):
    """PostSwitch201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSwitch201Response:
        """Test PostSwitch201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSwitch201Response`
        """
        model = PostSwitch201Response()
        if include_optional:
            return PostSwitch201Response(
                id = 56,
                name = '',
                description = '',
                switch_code = '',
                zone = sakura_vps_client_py.models.post_switch_201_response_zone.post_switch_201_response_zone(
                    code = 'tk2', 
                    name = '石狩第1', ),
                server_interfaces = [],
                nfs_server_interfaces = [],
                external_connection = None
            )
        else:
            return PostSwitch201Response(
                id = 56,
                name = '',
                description = '',
                switch_code = '',
                zone = sakura_vps_client_py.models.post_switch_201_response_zone.post_switch_201_response_zone(
                    code = 'tk2', 
                    name = '石狩第1', ),
                server_interfaces = [],
                nfs_server_interfaces = [],
                external_connection = None,
        )
        """

    def testPostSwitch201Response(self):
        """Test PostSwitch201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
