# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.problem_details404 import ProblemDetails404

class TestProblemDetails404(unittest.TestCase):
    """ProblemDetails404 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProblemDetails404:
        """Test ProblemDetails404
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProblemDetails404`
        """
        model = ProblemDetails404()
        if include_optional:
            return ProblemDetails404(
                code = 'not_found',
                message = '見つかりませんでした。'
            )
        else:
            return ProblemDetails404(
        )
        """

    def testProblemDetails404(self):
        """Test ProblemDetails404"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
