# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.nfs_server_contract import NfsServerContract

class TestNfsServerContract(unittest.TestCase):
    """NfsServerContract unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NfsServerContract:
        """Test NfsServerContract
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NfsServerContract`
        """
        model = NfsServerContract()
        if include_optional:
            return NfsServerContract(
                plan_code = 3439,
                plan_name = 'さくらのVPS(v5)  NFS 200GB OS03',
                service_code = '100000000000'
            )
        else:
            return NfsServerContract(
                plan_code = 3439,
                plan_name = 'さくらのVPS(v5)  NFS 200GB OS03',
                service_code = '100000000000',
        )
        """

    def testNfsServerContract(self):
        """Test NfsServerContract"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
