# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.get_role_list200_response import GetRoleList200Response

class TestGetRoleList200Response(unittest.TestCase):
    """GetRoleList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRoleList200Response:
        """Test GetRoleList200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRoleList200Response`
        """
        model = GetRoleList200Response()
        if include_optional:
            return GetRoleList200Response(
                count = 100,
                next = 'https://api.example.com/?page=3&per_page=10',
                previous = 'https://api.example.com/?per_page=10',
                results = [
                    sakura_vps_client_py.models.role.Role(
                        id = 56, 
                        name = '', 
                        description = '', 
                        permission_filtering = 'enabled', 
                        allowed_permissions = ["get-server-list","get-server","put-server"], 
                        resource_filtering = 'enabled', 
                        allowed_resources = sakura_vps_client_py.models.role_allowed_resources.Role_allowed_resources(
                            servers = [1,2,3], 
                            switches = [1,2,3], 
                            nfs_servers = [1,2,3], ), )
                    ]
            )
        else:
            return GetRoleList200Response(
                count = 100,
                next = 'https://api.example.com/?page=3&per_page=10',
                previous = 'https://api.example.com/?per_page=10',
                results = [
                    sakura_vps_client_py.models.role.Role(
                        id = 56, 
                        name = '', 
                        description = '', 
                        permission_filtering = 'enabled', 
                        allowed_permissions = ["get-server-list","get-server","put-server"], 
                        resource_filtering = 'enabled', 
                        allowed_resources = sakura_vps_client_py.models.role_allowed_resources.Role_allowed_resources(
                            servers = [1,2,3], 
                            switches = [1,2,3], 
                            nfs_servers = [1,2,3], ), )
                    ],
        )
        """

    def testGetRoleList200Response(self):
        """Test GetRoleList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
