# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.server_monitoring_settings_notification_incoming_webhook import ServerMonitoringSettingsNotificationIncomingWebhook

class TestServerMonitoringSettingsNotificationIncomingWebhook(unittest.TestCase):
    """ServerMonitoringSettingsNotificationIncomingWebhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerMonitoringSettingsNotificationIncomingWebhook:
        """Test ServerMonitoringSettingsNotificationIncomingWebhook
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerMonitoringSettingsNotificationIncomingWebhook`
        """
        model = ServerMonitoringSettingsNotificationIncomingWebhook()
        if include_optional:
            return ServerMonitoringSettingsNotificationIncomingWebhook(
                enabled = True,
                webhooks_url = '0',
                slack_team_name = '',
                slack_channel_name = ''
            )
        else:
            return ServerMonitoringSettingsNotificationIncomingWebhook(
                enabled = True,
                webhooks_url = '0',
                slack_team_name = '',
                slack_channel_name = '',
        )
        """

    def testServerMonitoringSettingsNotificationIncomingWebhook(self):
        """Test ServerMonitoringSettingsNotificationIncomingWebhook"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
