# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.get_server_list401_response import GetServerList401Response

class TestGetServerList401Response(unittest.TestCase):
    """GetServerList401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetServerList401Response:
        """Test GetServerList401Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetServerList401Response`
        """
        model = GetServerList401Response()
        if include_optional:
            return GetServerList401Response(
                code = 'not_authenticated',
                message = '認証情報が含まれていません。'
            )
        else:
            return GetServerList401Response(
        )
        """

    def testGetServerList401Response(self):
        """Test GetServerList401Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
