# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.switch_external_connection import SwitchExternalConnection

class TestSwitchExternalConnection(unittest.TestCase):
    """SwitchExternalConnection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwitchExternalConnection:
        """Test SwitchExternalConnection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwitchExternalConnection`
        """
        model = SwitchExternalConnection()
        if include_optional:
            return SwitchExternalConnection(
                service_code = '100000000000',
                type = 'cloud',
                services = [
                    sakura_vps_client_py.models.switch_external_connection_services_inner.Switch_external_connection_services_inner(
                        service_category = 'cloud', 
                        service_name = 'クラウド東京第1ゾーン', 
                        switch_code = '111111111111', )
                    ]
            )
        else:
            return SwitchExternalConnection(
                service_code = '100000000000',
                type = 'cloud',
                services = [
                    sakura_vps_client_py.models.switch_external_connection_services_inner.Switch_external_connection_services_inner(
                        service_category = 'cloud', 
                        service_name = 'クラウド東京第1ゾーン', 
                        switch_code = '111111111111', )
                    ],
        )
        """

    def testSwitchExternalConnection(self):
        """Test SwitchExternalConnection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
