# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.switch_external_connection_services_inner import SwitchExternalConnectionServicesInner

class TestSwitchExternalConnectionServicesInner(unittest.TestCase):
    """SwitchExternalConnectionServicesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwitchExternalConnectionServicesInner:
        """Test SwitchExternalConnectionServicesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwitchExternalConnectionServicesInner`
        """
        model = SwitchExternalConnectionServicesInner()
        if include_optional:
            return SwitchExternalConnectionServicesInner(
                service_category = 'cloud',
                service_name = 'クラウド東京第1ゾーン',
                switch_code = '111111111111'
            )
        else:
            return SwitchExternalConnectionServicesInner(
                service_category = 'cloud',
                service_name = 'クラウド東京第1ゾーン',
                switch_code = '111111111111',
        )
        """

    def testSwitchExternalConnectionServicesInner(self):
        """Test SwitchExternalConnectionServicesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
