# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.problem_details409 import ProblemDetails409

class TestProblemDetails409(unittest.TestCase):
    """ProblemDetails409 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProblemDetails409:
        """Test ProblemDetails409
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProblemDetails409`
        """
        model = ProblemDetails409()
        if include_optional:
            return ProblemDetails409(
                code = 'conflict',
                message = '状態の競合によりリクエストを処理できません。'
            )
        else:
            return ProblemDetails409(
        )
        """

    def testProblemDetails409(self):
        """Test ProblemDetails409"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
