# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.limitation import Limitation

class TestLimitation(unittest.TestCase):
    """Limitation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Limitation:
        """Test Limitation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Limitation`
        """
        model = Limitation()
        if include_optional:
            return Limitation(
                cpu_performance_limit = 'enabled',
                network_bandwidth_limit = 'enabled',
                outbound_port_25_blocking = 'enabled',
                storage_iops_limit = 'enabled'
            )
        else:
            return Limitation(
        )
        """

    def testLimitation(self):
        """Test Limitation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
