# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.put_server_ipv4_ptr_request import PutServerIpv4PtrRequest

class TestPutServerIpv4PtrRequest(unittest.TestCase):
    """PutServerIpv4PtrRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutServerIpv4PtrRequest:
        """Test PutServerIpv4PtrRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutServerIpv4PtrRequest`
        """
        model = PutServerIpv4PtrRequest()
        if include_optional:
            return PutServerIpv4PtrRequest(
                hostname = 'example.jp'
            )
        else:
            return PutServerIpv4PtrRequest(
                hostname = 'example.jp',
        )
        """

    def testPutServerIpv4PtrRequest(self):
        """Test PutServerIpv4PtrRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
