# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.server_monitoring_health import ServerMonitoringHealth

class TestServerMonitoringHealth(unittest.TestCase):
    """ServerMonitoringHealth unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerMonitoringHealth:
        """Test ServerMonitoringHealth
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerMonitoringHealth`
        """
        model = ServerMonitoringHealth()
        if include_optional:
            return ServerMonitoringHealth(
                last_checked_at = '2024-04-15T23:59:59+09:00',
                status = 'healthy',
                last_status_changed_at = '2024-04-01T23:59:59+09:00'
            )
        else:
            return ServerMonitoringHealth(
                last_checked_at = '2024-04-15T23:59:59+09:00',
                status = 'healthy',
                last_status_changed_at = '2024-04-01T23:59:59+09:00',
        )
        """

    def testServerMonitoringHealth(self):
        """Test ServerMonitoringHealth"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
