# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.problem_details400 import ProblemDetails400

class TestProblemDetails400(unittest.TestCase):
    """ProblemDetails400 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProblemDetails400:
        """Test ProblemDetails400
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProblemDetails400`
        """
        model = ProblemDetails400()
        if include_optional:
            return ProblemDetails400(
                code = 'invalid',
                message = 'Invalid input.',
                errors = {"foo":[{"code":"required","message":"この項目は必須です"}]}
            )
        else:
            return ProblemDetails400(
        )
        """

    def testProblemDetails400(self):
        """Test ProblemDetails400"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
