# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.nfs_server_ipv4 import NfsServerIpv4

class TestNfsServerIpv4(unittest.TestCase):
    """NfsServerIpv4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NfsServerIpv4:
        """Test NfsServerIpv4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NfsServerIpv4`
        """
        model = NfsServerIpv4()
        if include_optional:
            return NfsServerIpv4(
                address = '198.51.100.2',
                netmask = '255.255.254.0'
            )
        else:
            return NfsServerIpv4(
                address = '198.51.100.2',
                netmask = '255.255.254.0',
        )
        """

    def testNfsServerIpv4(self):
        """Test NfsServerIpv4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
