# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.server_monitoring_settings_health_check import ServerMonitoringSettingsHealthCheck

class TestServerMonitoringSettingsHealthCheck(unittest.TestCase):
    """ServerMonitoringSettingsHealthCheck unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerMonitoringSettingsHealthCheck:
        """Test ServerMonitoringSettingsHealthCheck
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerMonitoringSettingsHealthCheck`
        """
        model = ServerMonitoringSettingsHealthCheck()
        if include_optional:
            return ServerMonitoringSettingsHealthCheck(
                protocol = 'https',
                interval_minutes = 1,
                port = 80,
                host = '0',
                path = '/',
                basic_auth_username = '0',
                basic_auth_password = '0',
                status = 100,
                sni = True
            )
        else:
            return ServerMonitoringSettingsHealthCheck(
                protocol = 'https',
                interval_minutes = 1,
                port = 80,
                host = '0',
                path = '/',
                basic_auth_username = '0',
                basic_auth_password = '0',
                status = 100,
                sni = True,
        )
        """

    def testServerMonitoringSettingsHealthCheck(self):
        """Test ServerMonitoringSettingsHealthCheck"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
