# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.zone import Zone

class TestZone(unittest.TestCase):
    """Zone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Zone:
        """Test Zone
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Zone`
        """
        model = Zone()
        if include_optional:
            return Zone(
                id = 56,
                code = 'tk1',
                name = '',
                can_use_local = True,
                can_use_hybrid = True
            )
        else:
            return Zone(
                id = 56,
                code = 'tk1',
                name = '',
                can_use_local = True,
                can_use_hybrid = True,
        )
        """

    def testZone(self):
        """Test Zone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
