# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.server_interface import ServerInterface

class TestServerInterface(unittest.TestCase):
    """ServerInterface unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerInterface:
        """Test ServerInterface
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerInterface`
        """
        model = ServerInterface()
        if include_optional:
            return ServerInterface(
                id = 56,
                device = 'eth0',
                connectable_to_global_network = True,
                connect_to = 'global',
                mac = '9C:A3:BA:00:00:00',
                switch_id = 1
            )
        else:
            return ServerInterface(
                id = 56,
                device = 'eth0',
                connectable_to_global_network = True,
                connect_to = 'global',
                mac = '9C:A3:BA:00:00:00',
                switch_id = 1,
        )
        """

    def testServerInterface(self):
        """Test ServerInterface"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
