# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.api.switch_api import SwitchApi


class TestSwitchApi(unittest.TestCase):
    """SwitchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SwitchApi()

    def tearDown(self) -> None:
        pass

    def test_delete_switch(self) -> None:
        """Test case for delete_switch

        スイッチを削除する
        """
        pass

    def test_get_switch(self) -> None:
        """Test case for get_switch

        スイッチ情報を取得する
        """
        pass

    def test_get_switch_list(self) -> None:
        """Test case for get_switch_list

        スイッチ情報一覧を取得する
        """
        pass

    def test_post_switch(self) -> None:
        """Test case for post_switch

        スイッチを作成する
        """
        pass

    def test_put_switch(self) -> None:
        """Test case for put_switch

        スイッチ情報を更新する
        """
        pass


if __name__ == '__main__':
    unittest.main()
