# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.health_check_smtp import HealthCheckSmtp

class TestHealthCheckSmtp(unittest.TestCase):
    """HealthCheckSmtp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HealthCheckSmtp:
        """Test HealthCheckSmtp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthCheckSmtp`
        """
        model = HealthCheckSmtp()
        if include_optional:
            return HealthCheckSmtp(
                protocol = 'smtp',
                port = 25,
                interval_minutes = 1
            )
        else:
            return HealthCheckSmtp(
                protocol = 'smtp',
                port = 25,
                interval_minutes = 1,
        )
        """

    def testHealthCheckSmtp(self):
        """Test HealthCheckSmtp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
