# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.server_zone import ServerZone

class TestServerZone(unittest.TestCase):
    """ServerZone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerZone:
        """Test ServerZone
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerZone`
        """
        model = ServerZone()
        if include_optional:
            return ServerZone(
                code = 'tk1',
                name = '石狩第1'
            )
        else:
            return ServerZone(
                code = 'tk1',
                name = '石狩第1',
        )
        """

    def testServerZone(self):
        """Test ServerZone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
