# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.post_switch201_response_zone import PostSwitch201ResponseZone

class TestPostSwitch201ResponseZone(unittest.TestCase):
    """PostSwitch201ResponseZone unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSwitch201ResponseZone:
        """Test PostSwitch201ResponseZone
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSwitch201ResponseZone`
        """
        model = PostSwitch201ResponseZone()
        if include_optional:
            return PostSwitch201ResponseZone(
                code = 'tk2',
                name = '石狩第1'
            )
        else:
            return PostSwitch201ResponseZone(
                code = 'tk2',
                name = '石狩第1',
        )
        """

    def testPostSwitch201ResponseZone(self):
        """Test PostSwitch201ResponseZone"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
