# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.put_server_ipv4_ptr200_response import PutServerIpv4Ptr200Response

class TestPutServerIpv4Ptr200Response(unittest.TestCase):
    """PutServerIpv4Ptr200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PutServerIpv4Ptr200Response:
        """Test PutServerIpv4Ptr200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PutServerIpv4Ptr200Response`
        """
        model = PutServerIpv4Ptr200Response()
        if include_optional:
            return PutServerIpv4Ptr200Response(
                ptr = 'example.jp'
            )
        else:
            return PutServerIpv4Ptr200Response(
                ptr = 'example.jp',
        )
        """

    def testPutServerIpv4Ptr200Response(self):
        """Test PutServerIpv4Ptr200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
