# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.health_check_pop3 import HealthCheckPop3

class TestHealthCheckPop3(unittest.TestCase):
    """HealthCheckPop3 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HealthCheckPop3:
        """Test HealthCheckPop3
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthCheckPop3`
        """
        model = HealthCheckPop3()
        if include_optional:
            return HealthCheckPop3(
                protocol = 'pop3',
                port = 110,
                interval_minutes = 1
            )
        else:
            return HealthCheckPop3(
                protocol = 'pop3',
                port = 110,
                interval_minutes = 1,
        )
        """

    def testHealthCheckPop3(self):
        """Test HealthCheckPop3"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
