# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.api.api_key_api import ApiKeyApi


class TestApiKeyApi(unittest.TestCase):
    """ApiKeyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApiKeyApi()

    def tearDown(self) -> None:
        pass

    def test_delete_api_key(self) -> None:
        """Test case for delete_api_key

        APIキーを削除する
        """
        pass

    def test_delete_role(self) -> None:
        """Test case for delete_role

        ロールを削除する
        """
        pass

    def test_get_api_key(self) -> None:
        """Test case for get_api_key

        APIキーを取得する
        """
        pass

    def test_get_api_key_list(self) -> None:
        """Test case for get_api_key_list

        APIキーの一覧を取得する
        """
        pass

    def test_get_permission_list(self) -> None:
        """Test case for get_permission_list

        権限の一覧を取得する
        """
        pass

    def test_get_role(self) -> None:
        """Test case for get_role

        ロールを取得する
        """
        pass

    def test_get_role_list(self) -> None:
        """Test case for get_role_list

        ロール一覧を取得する
        """
        pass

    def test_post_api_key(self) -> None:
        """Test case for post_api_key

        APIキーを作成する
        """
        pass

    def test_post_api_key_rotate(self) -> None:
        """Test case for post_api_key_rotate

        APIキーのトークンのローテーションを行う
        """
        pass

    def test_post_role(self) -> None:
        """Test case for post_role

        ロールを作成する
        """
        pass

    def test_put_api_key(self) -> None:
        """Test case for put_api_key

        APIキーを更新する
        """
        pass

    def test_put_role(self) -> None:
        """Test case for put_role

        ロールを更新する
        """
        pass


if __name__ == '__main__':
    unittest.main()
