# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.server_ipv6 import ServerIpv6

class TestServerIpv6(unittest.TestCase):
    """ServerIpv6 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerIpv6:
        """Test ServerIpv6
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerIpv6`
        """
        model = ServerIpv6()
        if include_optional:
            return ServerIpv6(
                address = '2001:e42:102:1501:153:121:89:107',
                prefixlen = 64,
                gateway = 'fe80::1',
                nameservers = [
                    '2001:e42::1'
                    ],
                hostname = 'example.jp',
                ptr = 'example.jp'
            )
        else:
            return ServerIpv6(
                address = '2001:e42:102:1501:153:121:89:107',
                prefixlen = 64,
                gateway = 'fe80::1',
                nameservers = [
                    '2001:e42::1'
                    ],
                hostname = 'example.jp',
                ptr = 'example.jp',
        )
        """

    def testServerIpv6(self):
        """Test ServerIpv6"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
