# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.post_nfs_server_change_ipv4_request import PostNfsServerChangeIpv4Request

class TestPostNfsServerChangeIpv4Request(unittest.TestCase):
    """PostNfsServerChangeIpv4Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostNfsServerChangeIpv4Request:
        """Test PostNfsServerChangeIpv4Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostNfsServerChangeIpv4Request`
        """
        model = PostNfsServerChangeIpv4Request()
        if include_optional:
            return PostNfsServerChangeIpv4Request(
                address = '',
                netmask = ''
            )
        else:
            return PostNfsServerChangeIpv4Request(
                address = '',
                netmask = '',
        )
        """

    def testPostNfsServerChangeIpv4Request(self):
        """Test PostNfsServerChangeIpv4Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
