# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.nfs_storage_info import NfsStorageInfo

class TestNfsStorageInfo(unittest.TestCase):
    """NfsStorageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NfsStorageInfo:
        """Test NfsStorageInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NfsStorageInfo`
        """
        model = NfsStorageInfo()
        if include_optional:
            return NfsStorageInfo(
                free_space_kib = 411501820,
                usage_percentage = 1,
                capacity_kib = 411564672,
                usage_kib = 62852
            )
        else:
            return NfsStorageInfo(
                free_space_kib = 411501820,
                usage_percentage = 1,
                capacity_kib = 411564672,
                usage_kib = 62852,
        )
        """

    def testNfsStorageInfo(self):
        """Test NfsStorageInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
