# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.server import Server

class TestServer(unittest.TestCase):
    """Server unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Server:
        """Test Server
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Server`
        """
        model = Server()
        if include_optional:
            return Server(
                id = 56,
                name = '',
                description = '',
                service_type = 'linux',
                service_status = 'on_trial',
                cpu_cores = 2,
                memory_mebibytes = 1024,
                storage = [
                    sakura_vps_client_py.models.server_storage_inner.Server_storage_inner(
                        port = 0, 
                        type = 'ssd', 
                        size_gibibytes = 100, )
                    ],
                zone = sakura_vps_client_py.models.server_zone.Server_zone(
                    code = 'tk1', 
                    name = '石狩第1', ),
                options = [
                    'SQL Server Web Edition'
                    ],
                version = 'v5',
                ipv4 = sakura_vps_client_py.models.server_ipv4.Server_ipv4(
                    address = '198.51.100.2', 
                    netmask = '255.255.254.0', 
                    gateway = '198.51.100.1', 
                    nameservers = [
                        '203.0.113.1'
                        ], 
                    hostname = 'example.jp', 
                    ptr = 'example.jp', ),
                ipv6 = sakura_vps_client_py.models.server_ipv6.Server_ipv6(
                    address = '2001:e42:102:1501:153:121:89:107', 
                    prefixlen = 64, 
                    gateway = 'fe80::1', 
                    nameservers = [
                        '2001:e42::1'
                        ], 
                    hostname = 'example.jp', 
                    ptr = 'example.jp', ),
                contract = sakura_vps_client_py.models.server_contract.Server_contract(
                    plan_code = 3439, 
                    plan_name = 'さくらのVPS(v5)  1G IK01', 
                    service_code = '100000000000', ),
                power_status = 'power_on'
            )
        else:
            return Server(
                id = 56,
                name = '',
                description = '',
                service_type = 'linux',
                service_status = 'on_trial',
                cpu_cores = 2,
                memory_mebibytes = 1024,
                storage = [
                    sakura_vps_client_py.models.server_storage_inner.Server_storage_inner(
                        port = 0, 
                        type = 'ssd', 
                        size_gibibytes = 100, )
                    ],
                zone = sakura_vps_client_py.models.server_zone.Server_zone(
                    code = 'tk1', 
                    name = '石狩第1', ),
                options = [
                    'SQL Server Web Edition'
                    ],
                version = 'v5',
                ipv4 = sakura_vps_client_py.models.server_ipv4.Server_ipv4(
                    address = '198.51.100.2', 
                    netmask = '255.255.254.0', 
                    gateway = '198.51.100.1', 
                    nameservers = [
                        '203.0.113.1'
                        ], 
                    hostname = 'example.jp', 
                    ptr = 'example.jp', ),
                ipv6 = sakura_vps_client_py.models.server_ipv6.Server_ipv6(
                    address = '2001:e42:102:1501:153:121:89:107', 
                    prefixlen = 64, 
                    gateway = 'fe80::1', 
                    nameservers = [
                        '2001:e42::1'
                        ], 
                    hostname = 'example.jp', 
                    ptr = 'example.jp', ),
                contract = sakura_vps_client_py.models.server_contract.Server_contract(
                    plan_code = 3439, 
                    plan_name = 'さくらのVPS(v5)  1G IK01', 
                    service_code = '100000000000', ),
                power_status = 'power_on',
        )
        """

    def testServer(self):
        """Test Server"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
