# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.switch import Switch

class TestSwitch(unittest.TestCase):
    """Switch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Switch:
        """Test Switch
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Switch`
        """
        model = Switch()
        if include_optional:
            return Switch(
                id = 56,
                name = '',
                description = '',
                switch_code = '',
                zone = sakura_vps_client_py.models.switch_zone.Switch_zone(
                    code = 'tk1', 
                    name = '石狩第1', ),
                server_interfaces = [
                    56
                    ],
                nfs_server_interfaces = [
                    56
                    ],
                external_connection = sakura_vps_client_py.models.switch_external_connection.Switch_external_connection(
                    service_code = '100000000000', 
                    type = 'cloud', 
                    services = [
                        sakura_vps_client_py.models.switch_external_connection_services_inner.Switch_external_connection_services_inner(
                            service_category = 'cloud', 
                            service_name = 'クラウド東京第1ゾーン', 
                            switch_code = '111111111111', )
                        ], )
            )
        else:
            return Switch(
                id = 56,
                name = '',
                description = '',
                switch_code = '',
                zone = sakura_vps_client_py.models.switch_zone.Switch_zone(
                    code = 'tk1', 
                    name = '石狩第1', ),
                server_interfaces = [
                    56
                    ],
                nfs_server_interfaces = [
                    56
                    ],
                external_connection = sakura_vps_client_py.models.switch_external_connection.Switch_external_connection(
                    service_code = '100000000000', 
                    type = 'cloud', 
                    services = [
                        sakura_vps_client_py.models.switch_external_connection_services_inner.Switch_external_connection_services_inner(
                            service_category = 'cloud', 
                            service_name = 'クラウド東京第1ゾーン', 
                            switch_code = '111111111111', )
                        ], ),
        )
        """

    def testSwitch(self):
        """Test Switch"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
