# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.api.nfs_server_api import NfsServerApi


class TestNfsServerApi(unittest.TestCase):
    """NfsServerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NfsServerApi()

    def tearDown(self) -> None:
        pass

    def test_get_nfs_server(self) -> None:
        """Test case for get_nfs_server

        NFS情報を取得する
        """
        pass

    def test_get_nfs_server_interface(self) -> None:
        """Test case for get_nfs_server_interface

        NFSのインターフェースを取得する
        """
        pass

    def test_get_nfs_server_list(self) -> None:
        """Test case for get_nfs_server_list

        NFS情報一覧を取得する
        """
        pass

    def test_get_nfs_server_power_status(self) -> None:
        """Test case for get_nfs_server_power_status

        NFSの電源状態を取得する
        """
        pass

    def test_get_nfs_server_storage(self) -> None:
        """Test case for get_nfs_server_storage

        NFSのストレージ容量情報を取得する
        """
        pass

    def test_post_nfs_server_change_ipv4(self) -> None:
        """Test case for post_nfs_server_change_ipv4

        NFSのipv4を更新する
        """
        pass

    def test_post_nfs_server_force_reboot(self) -> None:
        """Test case for post_nfs_server_force_reboot

        NFSを強制再起動する
        """
        pass

    def test_post_nfs_server_power_on(self) -> None:
        """Test case for post_nfs_server_power_on

        NFSを起動する
        """
        pass

    def test_post_nfs_server_shutdown(self) -> None:
        """Test case for post_nfs_server_shutdown

        NFSをシャットダウンする
        """
        pass

    def test_put_nfs_server(self) -> None:
        """Test case for put_nfs_server

        NFS情報を更新する
        """
        pass

    def test_put_nfs_server_interface(self) -> None:
        """Test case for put_nfs_server_interface

        NFSのインターフェース情報を更新する
        """
        pass


if __name__ == '__main__':
    unittest.main()
