# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.get_api_key_list200_response import GetApiKeyList200Response

class TestGetApiKeyList200Response(unittest.TestCase):
    """GetApiKeyList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetApiKeyList200Response:
        """Test GetApiKeyList200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetApiKeyList200Response`
        """
        model = GetApiKeyList200Response()
        if include_optional:
            return GetApiKeyList200Response(
                count = 100,
                next = 'https://api.example.com/?page=3&per_page=10',
                previous = 'https://api.example.com/?per_page=10',
                results = [
                    sakura_vps_client_py.models.api_key.ApiKey(
                        id = 56, 
                        name = '', 
                        role = 56, 
                        token = '', )
                    ]
            )
        else:
            return GetApiKeyList200Response(
                count = 100,
                next = 'https://api.example.com/?page=3&per_page=10',
                previous = 'https://api.example.com/?per_page=10',
                results = [
                    sakura_vps_client_py.models.api_key.ApiKey(
                        id = 56, 
                        name = '', 
                        role = 56, 
                        token = '', )
                    ],
        )
        """

    def testGetApiKeyList200Response(self):
        """Test GetApiKeyList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
