# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.nfs_server import NfsServer

class TestNfsServer(unittest.TestCase):
    """NfsServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NfsServer:
        """Test NfsServer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NfsServer`
        """
        model = NfsServer()
        if include_optional:
            return NfsServer(
                id = 56,
                name = '',
                description = '',
                service_status = 'in_preparation',
                setting_status = 'done',
                storage = [
                    sakura_vps_client_py.models.nfs_server_storage_inner.NfsServer_storage_inner(
                        type = 'ssd', 
                        size_gibibytes = 100, )
                    ],
                zone = sakura_vps_client_py.models.server_zone.Server_zone(
                    code = 'tk1', 
                    name = '石狩第1', ),
                ipv4 = sakura_vps_client_py.models.nfs_server_ipv4.NfsServer_ipv4(
                    address = '198.51.100.2', 
                    netmask = '255.255.254.0', ),
                contract = sakura_vps_client_py.models.nfs_server_contract.NfsServer_contract(
                    plan_code = 3439, 
                    plan_name = 'さくらのVPS(v5)  NFS 200GB OS03', 
                    service_code = '100000000000', ),
                power_status = 'power_on'
            )
        else:
            return NfsServer(
                id = 56,
                name = '',
                description = '',
                service_status = 'in_preparation',
                setting_status = 'done',
                storage = [
                    sakura_vps_client_py.models.nfs_server_storage_inner.NfsServer_storage_inner(
                        type = 'ssd', 
                        size_gibibytes = 100, )
                    ],
                zone = sakura_vps_client_py.models.server_zone.Server_zone(
                    code = 'tk1', 
                    name = '石狩第1', ),
                ipv4 = sakura_vps_client_py.models.nfs_server_ipv4.NfsServer_ipv4(
                    address = '198.51.100.2', 
                    netmask = '255.255.254.0', ),
                contract = sakura_vps_client_py.models.nfs_server_contract.NfsServer_contract(
                    plan_code = 3439, 
                    plan_name = 'さくらのVPS(v5)  NFS 200GB OS03', 
                    service_code = '100000000000', ),
                power_status = 'power_on',
        )
        """

    def testNfsServer(self):
        """Test NfsServer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
