# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.get_server_list403_response import GetServerList403Response

class TestGetServerList403Response(unittest.TestCase):
    """GetServerList403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetServerList403Response:
        """Test GetServerList403Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetServerList403Response`
        """
        model = GetServerList403Response()
        if include_optional:
            return GetServerList403Response(
                code = 'permission_denied',
                message = 'このアクションを実行する権限がありません。'
            )
        else:
            return GetServerList403Response(
        )
        """

    def testGetServerList403Response(self):
        """Test GetServerList403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
