# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.server_ipv4 import ServerIpv4

class TestServerIpv4(unittest.TestCase):
    """ServerIpv4 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerIpv4:
        """Test ServerIpv4
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerIpv4`
        """
        model = ServerIpv4()
        if include_optional:
            return ServerIpv4(
                address = '198.51.100.2',
                netmask = '255.255.254.0',
                gateway = '198.51.100.1',
                nameservers = [
                    '203.0.113.1'
                    ],
                hostname = 'example.jp',
                ptr = 'example.jp'
            )
        else:
            return ServerIpv4(
                address = '198.51.100.2',
                netmask = '255.255.254.0',
                gateway = '198.51.100.1',
                nameservers = [
                    '203.0.113.1'
                    ],
                hostname = 'example.jp',
                ptr = 'example.jp',
        )
        """

    def testServerIpv4(self):
        """Test ServerIpv4"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
