# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.problem_details400_errors import ProblemDetails400Errors

class TestProblemDetails400Errors(unittest.TestCase):
    """ProblemDetails400Errors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProblemDetails400Errors:
        """Test ProblemDetails400Errors
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProblemDetails400Errors`
        """
        model = ProblemDetails400Errors()
        if include_optional:
            return ProblemDetails400Errors(
                non_field_errors = [
                    sakura_vps_client_py.models.invalid_parameter_detail_inner.InvalidParameterDetail_inner(
                        code = 'required', 
                        message = 'この項目は必須です', )
                    ]
            )
        else:
            return ProblemDetails400Errors(
        )
        """

    def testProblemDetails400Errors(self):
        """Test ProblemDetails400Errors"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
