# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.health_check_ssh import HealthCheckSsh

class TestHealthCheckSsh(unittest.TestCase):
    """HealthCheckSsh unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HealthCheckSsh:
        """Test HealthCheckSsh
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthCheckSsh`
        """
        model = HealthCheckSsh()
        if include_optional:
            return HealthCheckSsh(
                protocol = 'ssh',
                port = 22,
                interval_minutes = 1
            )
        else:
            return HealthCheckSsh(
                protocol = 'ssh',
                port = 22,
                interval_minutes = 1,
        )
        """

    def testHealthCheckSsh(self):
        """Test HealthCheckSsh"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
