# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sakura_vps_client_py.models.get_permission_list200_response import GetPermissionList200Response

class TestGetPermissionList200Response(unittest.TestCase):
    """GetPermissionList200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPermissionList200Response:
        """Test GetPermissionList200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPermissionList200Response`
        """
        model = GetPermissionList200Response()
        if include_optional:
            return GetPermissionList200Response(
                count = 100,
                next = 'https://api.example.com/?page=3&per_page=10',
                previous = 'https://api.example.com/?per_page=10',
                results = [
                    sakura_vps_client_py.models.permission.Permission(
                        code = 'get-server-list', 
                        name = 'サーバー一覧の取得', 
                        category = 'server', )
                    ]
            )
        else:
            return GetPermissionList200Response(
                count = 100,
                next = 'https://api.example.com/?page=3&per_page=10',
                previous = 'https://api.example.com/?per_page=10',
                results = [
                    sakura_vps_client_py.models.permission.Permission(
                        code = 'get-server-list', 
                        name = 'サーバー一覧の取得', 
                        category = 'server', )
                    ],
        )
        """

    def testGetPermissionList200Response(self):
        """Test GetPermissionList200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
