# coding: utf-8

"""
    さくらのVPS APIドキュメント

    Sakura VPS API client written in Python (generated with openapi-generator)

    The version of the OpenAPI document: 4.3.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ServerIpv6(BaseModel):
    """
    ServerIpv6
    """ # noqa: E501
    address: Optional[StrictStr] = Field(description="アドレス")
    prefixlen: Optional[StrictInt] = Field(description="プレフィックス長")
    gateway: Optional[StrictStr] = Field(description="ゲートウェイのアドレス")
    nameservers: List[StrictStr] = Field(description="ネームサーバーのアドレスリスト")
    hostname: Optional[StrictStr] = Field(description="標準ホスト名")
    ptr: Optional[StrictStr] = Field(description="逆引きホスト名")
    __properties: ClassVar[List[str]] = ["address", "prefixlen", "gateway", "nameservers", "hostname", "ptr"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServerIpv6 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if address (nullable) is None
        # and model_fields_set contains the field
        if self.address is None and "address" in self.model_fields_set:
            _dict['address'] = None

        # set to None if prefixlen (nullable) is None
        # and model_fields_set contains the field
        if self.prefixlen is None and "prefixlen" in self.model_fields_set:
            _dict['prefixlen'] = None

        # set to None if gateway (nullable) is None
        # and model_fields_set contains the field
        if self.gateway is None and "gateway" in self.model_fields_set:
            _dict['gateway'] = None

        # set to None if hostname (nullable) is None
        # and model_fields_set contains the field
        if self.hostname is None and "hostname" in self.model_fields_set:
            _dict['hostname'] = None

        # set to None if ptr (nullable) is None
        # and model_fields_set contains the field
        if self.ptr is None and "ptr" in self.model_fields_set:
            _dict['ptr'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServerIpv6 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "prefixlen": obj.get("prefixlen"),
            "gateway": obj.get("gateway"),
            "nameservers": obj.get("nameservers"),
            "hostname": obj.get("hostname"),
            "ptr": obj.get("ptr")
        })
        return _obj


