# coding: utf-8

"""
    さくらのVPS APIドキュメント

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ServerInterface(BaseModel):
    """
    ServerInterface
    """ # noqa: E501
    id: StrictInt = Field(description="id")
    display_name: StrictStr = Field(description="インターフェース名")
    connectable_to_global_network: StrictBool = Field(description="グローバルネットワークと接続可能か")
    connect_to: Optional[StrictStr] = Field(description="インターフェースの接続先")
    mac: StrictStr = Field(description="MACアドレス")
    switch_id: Optional[StrictInt] = Field(description="スイッチID")
    __properties: ClassVar[List[str]] = ["id", "display_name", "connectable_to_global_network", "connect_to", "mac", "switch_id"]

    @field_validator('display_name')
    def display_name_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['NIC1', 'NIC2', 'NIC3']):
            raise ValueError("must be one of enum values ('NIC1', 'NIC2', 'NIC3')")
        return value

    @field_validator('connect_to')
    def connect_to_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['switch', 'global']):
            raise ValueError("must be one of enum values ('switch', 'global')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServerInterface from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "display_name",
            "connectable_to_global_network",
            "connect_to",
            "mac",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if connect_to (nullable) is None
        # and model_fields_set contains the field
        if self.connect_to is None and "connect_to" in self.model_fields_set:
            _dict['connect_to'] = None

        # set to None if switch_id (nullable) is None
        # and model_fields_set contains the field
        if self.switch_id is None and "switch_id" in self.model_fields_set:
            _dict['switch_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServerInterface from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "display_name": obj.get("display_name"),
            "connectable_to_global_network": obj.get("connectable_to_global_network"),
            "connect_to": obj.get("connect_to"),
            "mac": obj.get("mac"),
            "switch_id": obj.get("switch_id")
        })
        return _obj


