# coding: utf-8

"""
    さくらのVPS APIドキュメント

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 5.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from sakura_vps_client_py.models.server_monitoring_settings_notification_email import ServerMonitoringSettingsNotificationEmail
from sakura_vps_client_py.models.server_monitoring_settings_notification_incoming_webhook import ServerMonitoringSettingsNotificationIncomingWebhook
from typing import Optional, Set
from typing_extensions import Self

class ServerMonitoringSettingsNotification(BaseModel):
    """
    ServerMonitoringSettingsNotification
    """ # noqa: E501
    email: ServerMonitoringSettingsNotificationEmail
    incoming_webhook: ServerMonitoringSettingsNotificationIncomingWebhook
    interval_hours: Annotated[int, Field(le=72, strict=True, ge=1)] = Field(description="再通知間隔(時間)")
    __properties: ClassVar[List[str]] = ["email", "incoming_webhook", "interval_hours"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ServerMonitoringSettingsNotification from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of email
        if self.email:
            _dict['email'] = self.email.to_dict()
        # override the default output from pydantic by calling `to_dict()` of incoming_webhook
        if self.incoming_webhook:
            _dict['incoming_webhook'] = self.incoming_webhook.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ServerMonitoringSettingsNotification from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email": ServerMonitoringSettingsNotificationEmail.from_dict(obj["email"]) if obj.get("email") is not None else None,
            "incoming_webhook": ServerMonitoringSettingsNotificationIncomingWebhook.from_dict(obj["incoming_webhook"]) if obj.get("incoming_webhook") is not None else None,
            "interval_hours": obj.get("interval_hours")
        })
        return _obj


